### PR TITLE
Upgrade to support ES 5.x, refs #11867

### PR DESCRIPTION
**Pull request by jraddaoui**
Upgrade Elasticsearch support from 1.x to 5.x. Main changes:

- Update Elastica to v5.3.1 and add new required deps.: Psr-fig/log and
  elasticsearch-php. The later requires PHP >= v5.6.6, so that should be
  the min. PHP version for AtoM after this changes.
- Fix ES status check on install process.
- Update ES index mappings:
  - String fields can now be keyword (not analyzed) or text (analyzed) and
    the not analyzed/analyzed value is not needed in the index property.
  - Remove include_in_all inside multi fields.
  - Set year_collected (from Artworks TMS data) to integer.
  - Change usage of index_analyzer to analyzer.
  - Increase total fields limit to 6000.
- Update ES/Elastica queries:
  - AtoM modules: fixed only list taxonomy terms query and remove browse
    elements from terms index page. Other modules shouldn't be hit in Binder.
  - Use setSize instead of setLimit.
  - Use setSource instead of setFields.
  - Use untouched fields for sorting.
  - Filters are replaced by queries, which can be applied as filters using the
    setPostFilter method from the queries. There is no query for the missing
    and not filters, they have been replaced by using a must_not clause in a
    bool query.
  - Replace facets by aggregations: big improvements in summary pages used
    from the dashboard and AIPs overview calculations. Small changes to format
    agg. data and to display it in the templates. Remove the need of file scripts
    by using the Painless language to write the scripts in the PHP actions.
  - Use scroll API for long result-sets instead of limiting to 99999 hits.
  - Avoid pagination over 10,000 records.

I have not renamed the HTML classes and ids related to the facets to avoid
making a lot of changes in the arDominionPlugin styles.

### CODE REVIEW

**Comment by mcantelon** [comment]
I didn't see anything that looked crazy in there, so should be good. 👍

**Comment by jraddaoui** [comment]
Thanks @mcantelon. I'll add the changes needed when paginating over 10000 records (explained via email to the group) and ping you for another review.

**Comment by jraddaoui** [comment]
Ready @mcantelon

**Comment by mcantelon** [comment]
Sorry I missed that... looks good to me! 👍

**Comment by jraddaoui** [comment]
Closing to create it against qa/0.9.x (equal to qa/0.8.x before we merge this)

**Comment by jraddaoui** [comment]
See https://github.com/artefactual/binder/pull/6

**Pull request closed without merging**
